---
- import_tasks: pre_requisite.yml
- include_tasks: packages.yml
  when:
  - "hostvars[inventory_hostname]['quagga_install_packages'] is defined"
  - "hostvars[inventory_hostname]['quagga_install_packages'] == 'true'"
  - "hostvars[inventory_hostname]['quagga_packages'] is defined"
  - "hostvars[inventory_hostname]['quagga_packages'] != ''"
- include_tasks: deploy_zebra.yml
  when:
  - "hostvars[inventory_hostname]['quagga_zebra_mgmt']"
  - "hostvars[inventory_hostname]['quagga_zebra_mgmt'] == 'true'"
- include_tasks: deploy_ospfd.yml
  when:
  - "hostvars[inventory_hostname]['quagga_ospfd_mgmt'] is defined"
  - "hostvars[inventory_hostname]['quagga_ospfd_mgmt'] == 'true'"
