---
- name: frr | Add the OS specific variables
  ansible.builtin.include_vars:
    file: "{{ hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: frr | Set facts about frr role
  ansible.builtin.set_fact:
    frr_daemons_settings: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].daemons[]') }}"
    frr_vtysh_settings: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].vtysh_options[]') }}"
    frr_init_settings: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].init_options[]') }}"
    frr_zebra_settings: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].settings[].zebra[]') }}"
    frr_vty_settings: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].settings[].vty[]') }}"
    frr_routes: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].settings[].routes[]') }}"
    frr_vrrp: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].settings[].vrrp[]') }}"
    frr_interfaces: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].settings[].interfaces[]') }}"
    frr_router_ospf_settings: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].settings[].router[].ospf[]') }}"
    frr_router_bgp_settings: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].settings[].router[].bgp[]') }}"
    frr_router_bgp_access_lists: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].settings[].router[].bgp_as_path_access_list[]') }}"
    frr_router_route_maps: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].settings[].router[].route_map[]') }}"
    frr_router_access_lists: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].settings[].router[].access_list[]') }}"
    frr_router_prefix_lists: "{{ hostvars[inventory_hostname]['frr'] |
      community.general.json_query('[].settings[].router[].prefix_list[]') }}"
- name: frr | Create frr catalog
  ansible.builtin.file:
    path: "{{ hostvars[inventory_hostname]['frr_conf_dest'] }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0750"
