---
- name: Validate zebra configuration
  command: "{{ hostvars[inventory_hostname]['quagga_zebra_service'] + ' -C -f ' + hostvars[inventory_hostname]['quagga_dest'] + '/' + hostvars[inventory_hostname]['quagga_zebra_service'] + '.conf' }}"
  register: "zebra_dry_run"
  failed_when: "zebra_dry_run.stderr != ''"
  when: "zebra_deploy_result|success"
  notify:
    - 'Enable zebra daemon'
    - 'Start zebra daemon'
- name: Validate ospfd configuration
  command: "{{ hostvars[inventory_hostname]['quagga_ospfd_service'] + ' -C -f ' + hostvars[inventory_hostname]['quagga_dest'] + '/' + hostvars[inventory_hostname]['quagga_ospfd_service'] + '.conf' }}"
  register: "ospfd_dry_run"
  failed_when: "ospfd_dry_run.stderr != ''"
  when: "ospfd_deploy_result|success"
  notify:
    - 'Enable ospfd daemon'
    - 'Start ospfd daemon'
- name: Validate multi ospfd configuration
  command: "{{ hostvars[inventory_hostname]['quagga_ospfd_service'] + ' -n ' + item|string + ' -C -f ' + hostvars[inventory_hostname]['quagga_dest'] + '/' + hostvars[inventory_hostname]['quagga_ospfd_service'] + '.conf' }}"
  with_items: "{{ hostvars[inventory_hostname]['quagga_ospfd_instances'] }}"
  register: "ospfd_multi_dry_run"
  failed_when: "ospfd_multi_dry_run.stderr != ''"
  when: "ospfd_multi_deploy_result|success"
  notify:
    - 'Enable multi ospfd daemon'
    - 'Start multi ospfd daemon'
- name: Enable zebra daemon
  service:
    name: "{{ hostvars[inventory_hostname]['quagga_zebra_service'] }}"
    enabled: "yes"
  when: "zebra_dry_run|success and hostvars[inventory_hostname]['quagga_enable'] == 'true'"
- name: Start zebra daemon
  service:
    name: "{{ hostvars[inventory_hostname]['quagga_zebra_service'] }}"
    state: "restarted"
  when: "zebra_dry_run|success and hostvars[inventory_hostname]['quagga_restart'] == 'true'"
- name: Enable ospfd daemon
  service:
    name: "{{ hostvars[inventory_hostname]['quagga_ospfd_service'] }}"
    enabled: "yes"
  when: "ospfd_dry_run|success and hostvars[inventory_hostname]['quagga_enable'] == 'true'"
- name: Start ospfd daemon
  service:
    name: "{{ hostvars[inventory_hostname]['quagga_ospfd_service'] }}"
    state: "restarted"
  when: "ospfd_dry_run|success and hostvars[inventory_hostname]['quagga_restart'] == 'true'"
- name: Enable multi ospfd daemon
  service:
    name: "{{ hostvars[inventory_hostname]['quagga_ospfd_instance_service'] + item|string }}"
    enabled: "yes"
  with_items: "{{ hostvars[inventory_hostname]['quagga_ospfd_instances'] }}"
  when: "ospfd_multi_dry_run|success and hostvars[inventory_hostname]['quagga_enable'] == 'true'"
- name: Start multi ospfd daemon
  service:
    name: "{{ hostvars[inventory_hostname]['quagga_ospfd_instance_service'] + item|string }}"
    state: "restarted"
  with_items: "{{ hostvars[inventory_hostname]['quagga_ospfd_instances'] }}"
  when: "ospfd_multi_dry_run|success and hostvars[inventory_hostname]['quagga_restart'] == 'true'"
